[build]
  publish = "dist"
  command = "npm run export"
[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/form"
  to = "https://forms.gle/JucM2t9MpqfwdLecA"
  status = 302
  force = true

[[redirects]]
  from = "/form/"
  to = "https://forms.gle/JucM2t9MpqfwdLecA"
  status = 302
  force = true

[[redirects]]
  from = "/resume"
  to = "https://blog.luispa.dev/static/resume_luis_garcia.pdf"
  status = 302
  force = true

[[redirects]]
  from = "/resume/"
  to = "https://blog.luispa.dev/static/resume_luis_garcia.pdf"
  status = 302
  force = true

[[redirects]]
from = "/gaby/procedimientos-civiles-y-familiares"
to = "/static/codigo-nacional-de-procedimientos-civiles-y-familiares.pdf"
status = 302
force = true

[[redirects]]
from = "/gaby/codigo-general-del-proceso"
to = "/static/Leyes desde 1992 - Vigencia expresa y control de constitucionalidad [LEY_1564_2012].pdf"
status = 302
force = true

[[redirects]]
from = "/gaby/codigo-general-del-proceso-2"
to = "/static/codigo-general-proceso-uruguay.pdf"
status = 302
force = true

[[redirects]]
from = "/gaby/decreto-806-de-2020"
to = "/static/3Decreto_806_de_2020.pdf"
status = 302
force = true
